### ISSUE TITLE
ssh to the internal ip of AKS node

### ISSUE THREAD

**Issue by giuliohome** [cloudziu/debugging-scratch#1]
Thank you for the fantastic blog post! I don't think it's a realistic way of debugging, as it requires elevated privileges that application teams might not have. However, it provides a deep dive into Linux namespaces and Kubernetes networking.

A note to myself:

A cluster public IP is unnecessary; the internal IP of the node suffices.

I used the modified security-context-4.yaml:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-4
spec:
  containers:
  - name: sec-ctx-4
    image: nicolaka/netshoot:v0.11
    command: ["/bin/sleep", "infinity"]
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
```

and ran:

```sh
kubectl apply -f security-context-4.yaml
kubectl cp ~/.ssh/lab_rsa security-context-demo-4:/lab_rsa
kubectl exec -it security-context-demo-4 -- zsh
```

Finally:

```sh
ssh -vv -i /lab_rsa azureuser@10.224.0.4
```

assuming that `10.224.0.4` was the node ip (then in the worker node I had to use `sudo` with `df`, `nsenter`, etc... therefore something was slightly different, because `cd` and a direct `echo` to the `/proc` directory were not possible, but there was an easy workaround).
